# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: out5
version: '0.2'
author: 'Oliver Kreischer'
supportpage: www.redaxo.org/de/forum/

page:
    title: 'out5'
    perm: out5[]
    icon: rex-icon fa-gears
    subpages:
        uebersicht: { title: 'Übersicht' }
        info: { title: 'Info' }
