# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: out5
version: '1.1.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/out5

page:
    title: 'out5'
    perm: out5[]
    icon: rex-icon fa-gears
    subpages:
        uebersicht: { title: 'Übersicht' }
        info: { title: 'Info' }
