# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: be5
version: '0.1'
author: Oliver Kreischer
supportpage: www.redaxo.org/de/forum
title: 'BE5'
page:
    title: 'BE5'
    perm: be5[]
    icon: rex-icon fa-gears
    subpages:
        main:
          title: 'Info'
          subpages:
            index: {title:'Übersicht', hidden: true}
